# Generated by Django 2.2.7 on 2020-03-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_index', models.BigIntegerField(default=0)),
                ('broken', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('partial', models.BooleanField(default=False)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certstreams.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_filtered', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certstreams.Issuer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certstreams.Source')),
            ],
        ),
    ]
