# Generated by Django 3.0.3 on 2020-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certstreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='matching_endswith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='matching_startswith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
