# Generated by Django 3.0.3 on 2020-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certstreams', '0002_auto_20200320_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
